=== tobidot/html-adventure/src/schema/interactable.dtd
<!ELEMENT game-interactable (
        game-data, img, object
        )>
        <!ELEMENT div (#PCDATA)>
        <!ELEMENT object (#PCDATA)>
        <!ELEMENT img (#PCDATA)>
        <!ELEMENT game-data (game-data-property*,game-data-action*)>
        <!ELEMENT game-data-property EMPTY>
        <!ELEMENT game-data-action (game-logic|game-logic-condition|game-logic-action|game-logic-option)+>
        <!ELEMENT game-logic (game-logic|game-logic-condition|game-logic-action|game-logic-option)+>
        <!ELEMENT game-logic-option (game-logic|game-logic-condition|game-logic-action|game-logic-option)+>
        <!ELEMENT game-logic-condition (game-logic|game-logic-condition|game-logic-action|game-logic-option)+>
        <!ELEMENT game-logic-action (#PCDATA)>

        <!ATTLIST game-interactable
                id     ID       #REQUIRED
                style  PCDATA    #IMPLIED
                class  PCDATA    #REQUIRED
                >

        <!ATTLIST game-data
                class  PCDATA    #FIXED "data"
                >

        <!ATTLIST game-data-property
                key    PCDATA    #REQUIRED
                value  PCDATA    #REQUIRED
                >

        <!ATTLIST game-data-action
                type   PCDATA    #REQUIRED
                using  PCDATA    #IMPLIED
                ref NMTOKEN #IMPLIED
                >

        <!ATTLIST game-logic
                type   PCDATA    #REQUIRED
                ref NMTOKEN #IMPLIED
                >

        <!ATTLIST game-logic-condition
                key             PCDATA      #REQUIRED
                value           PCDATA      #REQUIRED
                operator        PCDATA      #IMPLIED
                ref   NMTOKEN     #IMPLIED
                >

        <!ATTLIST game-logic-option
                text   PCDATA    #REQUIRED
                index  PCDATA    #IMPLIED
                ref NMTOKEN #IMPLIED
                >

        <!ATTLIST game-logic-action
                type   PCDATA    #REQUIRED
                key   PCDATA    #IMPLIED
                value PCDATA    #IMPLIED
                >


        <!ATTLIST img
                id     ID       #IMPLIED
                class  PCDATA    #FIXED "image"
                src    PCDATA    #REQUIRED
                alt    PCDATA    #REQUIRED
                >

        <!ATTLIST object
                id     ID       #IMPLIED
                class  PCDATA    #FIXED "click-area"
                type   PCDATA    #FIXED "image/svg+xml"
                data   PCDATA    #REQUIRED
                >

=== tobidot/html-adventure/src/html/objects/examples/dad.xml
<!DOCTYPE game-interactable SYSTEM "interactable.dtd">
<game-interactable id="dad" class="object" style="{=$style}">
    <game-data class="data">
        <game-data-property key="name" value="Old Dad"></game-data-property>
        <game-data-property key="location" value="Living Room"></game-data-property>
        <game-data-action type="inspect">
            <game-logic-action type="output">
                My Dad, ... I like him, but I wish he wasn't as sarcastic.
            </game-logic-action>
        </game-data-action>
        <game-data-action type="talk">
            <game-logic type="all">
                <game-logic-option text="Hey Dad, what do you think about what I'm doing?">
                    <game-logic-action type="output">
                        Old Dad: 'Well, isn't this a surprise! Thought you'd never ask an old man for advice.'
                    </game-logic-action>
                    <game-logic-action type="output">
                        Old Dad: 'Doing? You're almost as busy as a cat on a hot tin roof, just less productive!'
                    </game-logic-action>
                </game-logic-option>
                <game-logic-option text="Come on, Dad, be serious for a second.">
                    <game-logic-action type="output">
                        Old Dad: 'Serious? Alright, I think it's fantastic to see you tackling things head-on, just
                        maybe tackle them a bit softer next time!'
                    </game-logic-action>
                </game-logic-option>
                <game-logic-option text="Oh yeah? And what would make it productive, Oh wise one?">
                    <game-logic-action type="output">
                        Old Dad: 'Wisdom, huh? First rule: never argue with an old man whoâ€™s seen your baby photos!'
                    </game-logic-action>
                </game-logic-option>
            </game-logic>
        </game-data-action>
    </game-data>
    <img
            class="image"
            src="./images/dummy.png"
data-src="./images/objects/dad/dad.png"
            alt=""
    />
    <object
            class="click-area"
            data="./images/dummy.png"
data-data="/public/images/objects/dad/dad.svg"
            type="image/svg+xml"
    > </object>
</game-interactable>

=== tobidot/html-adventure/src/html/objects/examples/template-object.xml
<!DOCTYPE game-interactable SYSTEM "interactable.dtd">
<game-interactable id="unknown" class="object" style="{=$style}">
    <!-- This is a template object. replace the 'unknown' in this file -->
    <game-data class="data">
        <game-data-action type="inspect">
            <game-logic-action type="output">
                ...
            </game-logic-action>
        </game-data-action>
        <game-data-action type="interact">
        </game-data-action>
        <game-data-action type="pick-up">
        </game-data-action>
        <game-data-action type="talk">
            <game-logic-action type="output">
                ...
            </game-logic-action>
        </game-data-action>
    </game-data>
    <img
            class="image"
            src="./images/dummy.png"
data-src="./images/objects/unknown/unknown.png"
            alt=""
    />
    <object
            class="click-area"
            data="./images/dummy.png"
data-data="/assets/images/objects/unknown/unknown.svg"
            type="image/svg+xml"
    > </object>
</game-interactable>

=== tobidot/html-adventure/src/docs/v1/example-object.xml
<!DOCTYPE game-interactable SYSTEM "interactable.dtd">
<game-interactable id="example" class="object" style="{=$style}">
    <!-- This is an example object. See different parts of it to understand the logical behaviours -->
    <!-- The game-data element contains the logic for the object, how does it interact with the world -->
    <game-data class="data">
        <!-- This is a property of the object, it can be referenced later in other logic -->
        <game-data-property key="mood" value="angry"> </game-data-property>
        <!--
            The <game-data-action> element is a starting point for interactive logic.
            A <game-logic> element functions as a container for multiple logics to perform, it can define the flow of logic.
            With <game-logic-condition> it is possible to branch the logic based on conditions.
            On a <game-logic-option> the player can choose is provided the option to trigger the inner logic, it's used for dialogue.
            The <game-logic-action> is the endpoint of a logic, it performs an actual change on the game.

            The logic elements are executed in order and by default all children are executed.
        -->
        <!--
            The "inspect" action is triggered when the player wants to know more about the object.
            It should in most cases just output a description of the object.
        -->
        <game-data-action type="inspect">
            <!-- The "output" action simply prints and reads the text inside it out loud. -->
            <game-logic-action type="output">
                The example object is a mystery to you. It is a strange object, you have never seen anything like it
                before.
            </game-logic-action>
        </game-data-action>
        <!--
            The "interact" action is triggered when the player wants the object to do something.
        -->
        <game-data-action type="interact">
            <!--
                There are several ways to reference and obtain values inside a condition element.
                The first character determines the source of the reference, the following characters determine the value itself.
            -->
            <!-- '@' is used to reference a property of the parent object, in this case the mood property declared above. -->
            <!-- '!' is used to make sure this value is a raw value, not a reference. You can also just omit the '!' -->
            <game-logic-condition key="@mood" value="!chill">
                <!-- The 'set-variable' allows for changing values, here we set the mood property of this object to te literal value "angry" -->
                <game-logic-action type="set-variable" key="@.mood" value="angry"> </game-logic-action>
                <game-logic-action type="output">The object is now angry</game-logic-action>
            </game-logic-condition>
            <!-- '#' can be used to reference a property of any object, in this case we are referencing by it by id defined in the 'game-interactable' element -->
            <!-- After the source element is defined either by (#element or @) it can be followed by a '.' to simply select for a property with that key on that object -->
            <game-logic-condition key="#example.mood" value="angry">
                <game-logic-action type="output">Object: Summm!</game-logic-action>
            </game-logic-condition>
            <!-- If the element is followed by a '?' the rest will be interpreted as a query selector and the value will be the number of matches for that selector -->
            <!-- In this case we are checking if the player has any bread in their inventory -->
            <game-logic-condition key="#inventory?#bread" operator="greater" value="0">
                <game-logic-action type="set-variable" key="@.mood" value="angry"> </game-logic-action>
                <game-logic-action type="output">Object: Swirrr...</game-logic-action>
                <game-logic-action type="output">The object sounds happy now.</game-logic-action>
            </game-logic-condition>
        </game-data-action>
        <!-- The "pick-up" action is triggered when the player wants to take the object with them into their inventory. -->
        <game-data-action type="pick-up">
            <!-- This should add the object to the player's inventory -->
            <!-- value is the id of the object to be added to the inventory -->
            <game-logic-action type="add-inventory" value="example"> </game-logic-action>
        </game-data-action>
        <!-- The "talk" action is triggered when the player wants to lost-forest a dialogue. -->
        <game-data-action type="talk">
            <!-- This is an option for the player to choose from, it should be a question or a statement -->
            <game-logic-option text="Hello?">
                <!-- once an option is picked it will remove itself from the option-list and trigger the inner logic -->
                <game-logic-action type="output">The object does not respond.</game-logic-action>
            </game-logic-option>
            <!-- The index attribute is used to determine the order of the options, the option to end a dialogue usually is at the end of the list -->
            <game-logic-option text="(Leave it alone)" index="10" >
                <!-- This action ends the interaction and removes all options -->
                <game-logic-action type="end-interaction"> </game-logic-action>
            </game-logic-option>
            <!-- The index attribute is used to determine the order of the options, the option to end a dialogue usually is at the end of the list -->
            <game-logic-option text="Bring me to the town!">
                <!-- This action is meant to open another scene, the value is the id of the scene, with an implicit 'scene-' as a prefix -->
                <game-logic-action type="change-scene" value="town"> </game-logic-action>
            </game-logic-option>
            <!-- The index attribute is used to determine the order of the options, the option to end a dialogue usually is at the end of the list -->
            <game-logic-option text="(Show to)">
                <!-- This action will attach the referenced object to the cursor, allowing the user to combine it with other objects -->
                <game-logic-action type="add-cursor" value="example"> </game-logic-action>
            </game-logic-option>
        </game-data-action>
        <!-- The combine action is triggered, when the user currently carries another item and clicked on this object -->
        <game-data-action type="combine">
            <!-- the global variable $using is set to the id of the object the player is currently using -->
            <game-logic-condition key="$using" value="bread">
                <game-logic-action type="output">
                    The object is not interested in the bread.
                </game-logic-action>
            </game-logic-condition>
        </game-data-action>
    </game-data>
    <!--
     The image element contains the visual representation of the object, it will be displayed on the screen
     the 'alt' attribute is used for midjourney to generate an image from for the object.
     -->
    <img
            class="image"
            src="./images/objects/example/example.png"
            alt="An image of the example object, white background, sprite-sheet, Dos Adventure Game, Low Definition, Low Quality Art, Dithering, cropped out, object only"
    />
    <!--
            The object element is the clickable area of the object it will be generated from the image.
            -->
    <object
            class="click-area"
            data="./images/objects/example/example.svg"
            type="image/svg+xml"
    />
</game-interactable>

=== tobidot/html-adventure/src/html/objects/farmer.xml
<!DOCTYPE game-interactable SYSTEM "interactable.dtd">
<game-interactable id="farmer01" class="object" style="position: absolute; top: 100px; left: 200px;">
    <game-data class="data">
        <game-data-property key="mood" value="anxious"/>
        <game-data-property key="occupation" value="farmer"/>
        <game-data-action type="inspect">
            <game-logic-action type="output">
                You notice a jittery farmer pacing back and forth. Despite his rugged appearance, there's a palpable sense of unease about him as he mutters under his breath about his harvest.
            </game-logic-action>
        </game-data-action>
        <game-data-action type="interact">
            <game-logic-option text="The crops look healthy despite the tough season, how do you manage?">
                <game-logic-action type="output">
                    The farmer smiles weakly, "Thank you! It’s a secret, but hard work and a bit of old wisdom go a long way. And avoiding tall taxes when we can, which isn't often."
                </game-logic-action>
            </game-logic-option>
            <game-logic-option text="Your family seems strong. How do they feel about all the hard work?">
                <game-logic-action type="output">
                    The farmer sighs, "They’re my pride. Hardworking and never complaining. But deep down, I know they wish for a life beyond these fields and unfair decrees."
                </game-logic-action>
            </game-logic-option>
            <game-logic-option text="What’s your opinion on the king’s ruling?">
                <game-logic-condition key="fear" value="10" operator="more_than">
                    <game-logic-action type="output">
                        The farmer glances around fearfully, "Best not to ask such things, stranger. Walls have ears and the trees, eyes."
                    </game-logic-action>
                </game-logic-condition>
                <game-logic-condition key="fear" value="5" operator="less_than">
                    <game-logic-action type="output">
                        The farmer leans in, whispering cautiously, "Our king? More a tyrant than a ruler. But don’t spread that, I have my children to think about."
                    </game-logic-action>
                </game-logic-condition>
            </game-logic-option>
            <game-logic-option text="Can I assist you in any way against these oppressions?">
                <game-logic-action type="output">
                    The farmer's eyes light up with a spark of hope, "Bless you! Perhaps, spread the word? Or just keep buying our produce. Every bit helps."
                </game-logic-action>
            </game-logic-option>
        </game-data-action>
    </game-data>
    <img id="farmer01Image" class="image" src="farmer.svg" alt="Wizened Farmer"/>
    <object id="farmer01Object" class="click-area" type="image/svg+xml" data="farmerInteractive.svg"/>
</game-interactable>
